CREATE OR REPLACE PACKAGE SRS 
AS 
  TYPE REF_CURSOR IS REF CURSOR; 
  PROCEDURE SHOW_STUDENTS ( 
    OUTCURSOR OUT REF_CURSOR); 
  PROCEDURE SHOW_TAS ( 
    OUTCURSOR OUT REF_CURSOR); 
  PROCEDURE SHOW_COURSES ( 
    OUTCURSOR OUT REF_CURSOR); 
  PROCEDURE SHOW_CLASSES ( 
    OUTCURSOR OUT REF_CURSOR); 
  PROCEDURE SHOW_ENROLLMENTS ( 
    OUTCURSOR OUT REF_CURSOR); 
  PROCEDURE SHOW_PREREQUISITES ( 
    OUTCURSOR OUT REF_CURSOR); 
  PROCEDURE SHOW_LOGS ( 
    OUTCURSOR OUT REF_CURSOR); 
  PROCEDURE GET_TA_FOR_CLASS( 
    CLASSID_IN IN CLASSES.CLASSID%TYPE, 
    OUTCURSOR  OUT REF_CURSOR); 
  PROCEDURE GET_PREREQUISITE ( 
    DEPT_CODE_IN IN PREREQUISITES.DEPT_CODE%TYPE, 
    COURSE#_IN   IN PREREQUISITES.COURSE#%TYPE, 
    OUTCURSOR    OUT REF_CURSOR); 
  PROCEDURE ENROLL_STUDENT( 
    B#_IN      IN STUDENTS.B#%TYPE, 
    CLASSID_IN IN CLASSES.CLASSID%TYPE); 
  PROCEDURE DROP_STUDENT ( 
    B#_IN      IN STUDENTS.B#%TYPE, 
    CLASSID_IN IN CLASSES.CLASSID%TYPE); 
  PROCEDURE DELETE_STUDENT ( 
    B#_IN IN STUDENTS.B#%TYPE); 
END; 

/ 
show ERRORS